# Generated by Django 4.0.5 on 2022-06-21 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=60, verbose_name='TITLE_RU')),
                ('title_eng', models.CharField(max_length=60, verbose_name='TITLE_ENG')),
                ('year_of_issue', models.DateField(verbose_name='YEAR_OF_ISSUE')),
                ('duration', models.DurationField(verbose_name='DURATION')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='RATING')),
                ('synopsis', models.CharField(max_length=250, verbose_name='SYNOPSIS')),
                ('trailer_link', models.TextField(verbose_name='TRAILER_LINK')),
                ('img_cover', models.TextField(verbose_name='IMG_COVER')),
                ('img_small', models.TextField(verbose_name='IMG_SMALL')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='GENRE_TITLE')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='LOGIN')),
                ('email', models.CharField(max_length=50, verbose_name='EMAIL')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='USER_RATING')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='film', to='bibaboba.film')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user', to='bibaboba.user')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='bibaboba.user'),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='bibaboba.genre'),
        ),
    ]
