# Generated by Django 4.0.5 on 2022-06-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibaboba', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='type',
            field=models.CharField(max_length=25, null=True, verbose_name='TYPE'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='film_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='film_id', to='bibaboba.film'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_id', to='bibaboba.user'),
        ),
    ]
