# Generated by Django 4.0.5 on 2022-06-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibaboba', '0003_film_type_alter_userrating_film_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='TYPE_NAME')),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bibaboba.type'),
        ),
    ]
